### ISSUE TITLE
abcjs quotation and apostrophe issue

### ISSUE THREAD

**Issue by smbutterfield** [smbutterfield/ibmt17-18#1]
I found your explanation of needing to use either an apostrophe or quotation to set off the abc notation in an include. Unfortunately, it can be necessary to use both of these in the notation. The apostrophe is affixed to pitch names to raise the octave. (Most important) The quotation is used in in the voice function for the header to contain phrases that need more than one word. E.g. V:1 name="Violin 1" -- Without quotations, the "1" will not be included in the name on that line. (Less important)

Any ideas?

**Comment by evanwill** [comment]
ha ha, just working on this as you opened the issue. 
next push offers one solution

**Comment by evanwill** [comment]
see updated [abc-include doc](https://github.com/smbutterfield/ibmt17-18/blob/master/docs/abc-include.md).

**Comment by evanwill** [comment]
using capture as outlined above works. It's a bit more of a hassle.

Another option would be to create a abc-notation folder, and have each tune as a file. Then to include the tune, you would designate the filename. Not sure if that is more organized or confusing...

**Comment by smbutterfield** [comment]
I think the most straight-forward solution is to just minimize the usage of multi-word variables in the voice line. This could be somewhat limiting in certain contexts, but using the capture seems like more work than it's worth for a problem that will only come up infrequently.

**Comment by smbutterfield** [comment]
For now, I'll just need to remember that if I need to use multi-word variables for naming staves, I need to use nothing above the 5th ISO octave. Thanks!

**Comment by evanwill** [comment]
You can use either way (inline with quotes, or use the capture tag), so you can keep using the inline--then if you need both in your abc, just switch to the capture tag.
