### ISSUE TITLE
abcjs midi requires M: to be set

### ISSUE THREAD

**Issue by evanwill** [smbutterfield/ibmt17-18#2]
I noticed some examples with `M:` left open. abcjs renders the notation, but midi play back doesn't work because the code is looking for a meter variable. 

I replaced the blank `M:`s with `M: 4/4`, not sure what you actually want in them.

**Comment by smbutterfield** [comment]
Hmm. I was using the editor on the abcjs site as a testing ground until we get ours up and running, and I could leave the `M:` blank if I didn't want any meter at all. I'll go through and insert a placeholder meter for those. Good to know.

**Comment by evanwill** [comment]
On the abcjs site it doesn't work either--but he put something in so that if there is an error it just doesnt update, so it looks like it is still working, but you'll notice the music isn't changing.
