### ISSUE TITLE
2a content creation page failure

### ISSUE THREAD

**Issue by smbutterfield** [smbutterfield/ibmt17-18#5]
Hi Evan,

Having a massive page build failure on my latest commit -- 2a content creation. I'll keep working on trying to figure out what I screwed up, but if you have a moment, I'd appreciate a hand. Thanks in advance!

**Comment by evanwill** [comment]
you just left off the closing tag on the abc includes, i.e. has to end with `%}`

I just pushed the fix, should be fine now!

**Comment by evanwill** [comment]
for reference: when github sends out those page build errors, your site doesn't go offline, it just can't update until the jekyll issue is fixed. So the error doesn't cause downtime or broken links--it just won't be updated.
